### PR TITLE
Auto-Generate API-Key on Creation

### PR DESCRIPTION
**Pull request by Sn0w3y**

### CODE REVIEW

**Comment by sfeilmeier** [comment]
@mlang97 What do you think? Looks good to me.

**Comment by mxlang** [comment]
Thank you @Sn0w3y for your contribution. The changes look good to me. I think the apikey should be unique. @Sn0w3y what do you think? Maybe you can do this cahnge. Thank you!

**Comment by Sn0w3y** [comment]
> Thank you @Sn0w3y for your contribution. The changes look good to me. I think the apikey should be unique. @Sn0w3y what do you think? Maybe you can do this cahnge. Thank you!

100% - will Implement this definitely!

**Comment by Sn0w3y** [comment]
Should be feasable now ! :)

Greetings

**Comment by Sn0w3y** [comment]
Updated it again, so it generates API-Key and setup_password unique and automatically ! :)

**Comment by Sn0w3y** [comment]
Tested, working now.

**Comment by Sn0w3y** [comment]
Again, tested, Added check for the Device Name - see here:

originally Device.name field is readonly in webui to avoid mis-operation when updating device information and force to use API.

this commit changes Device.name field can be edit when creating by using odoo custom constraints.

if you want to know detail of original code requirement and background, see also https://github.com/OpenEMS/odoo-openems/pull/4#pullrequestreview-1754089294

Improved it by not using the filed but the Database for the check (performance is better if more Datasets are loaded)

@mlang97

**Review by sfeilmeier — APPROVED** [review]

**Pull request merged**
